<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0;net10.0-windows</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <NekoRayProjectId>neuro</NekoRayProjectId>
        <CopyAllData>true</CopyAllData>
        <PackageId>NeuroSama</PackageId>
    </PropertyGroup>

    <Import Project="../NekoRay/game.targets"/>

    <ItemGroup>
        <ProjectReference Include="..\NekoRay\NekoRay.csproj"/>
    </ItemGroup>

    <ItemGroup>
      <None Update=".itch.toml">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="neuro\sprites\location1_fg.nrs">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="neuro\sprites\characters\neuro\walk_1.nrs">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="neuro\sprites\characters\neuro\walk_2.nrs">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="neuro\sprites\characters\neuro\walk_3.nrs">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="neuro\sprites\characters\neuro\walk_4.nrs">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="neuro\sprites\characters\neuro\walk_5.nrs">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="neuro\sprites\characters\neuro\walk_6.nrs">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="neuro\sprites\characters\neuro\walk_7.nrs">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="neuro\sprites\characters\neuro\walk_8.nrs">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="neuro\sprites\characters\neuro\walk_9.nrs">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="neuro\sprites\characters\neuro\walk_10.nrs">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="neuro\animations\characters\neuro\walk.toml">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="neuro\sprites\dialogues\vedal neutral.nrs">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="neuro\sprites\minigame\answer_2.nrs">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="neuro\sprites\minigame\answer_3.nrs">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="neuro\sprites\minigame\question_1.nrs">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="neuro\sprites\minigame\ballpit_text.nrs">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="neuro\sprites\minigame\tutel.nrs">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
