<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0;net10.0-windows</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <NekoRayProjectId>th</NekoRayProjectId>
        <CopyAllData>true</CopyAllData>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\NekoRay\NekoRay.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="th\textures\characters\reimu.qoi">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="th\sprites\characters\reimu\idle.nrs">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>
    
    <Import Project="../NekoRay/game.targets" />

</Project>
