<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFrameworks>net10.0;net10.0-windows</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Company>VanderCat</Company>
        <Product>NekoRay Silly Engine</Product>
        <AssemblyVersion>2.0</AssemblyVersion>
        <LangVersion>preview</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <AssemblyAttribute Include="NekoRay.DefaultGameIdAttribute">
            <_Parameter1>$(NekoRayDefaultGameId)</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\..\box2c-sharp\Box2D\Box2D.csproj" />
      <ProjectReference Include="..\..\box2c-sharp\Box2D.Interop\Box2D.Interop.csproj" />
      <ProjectReference Include="..\..\rlImGui-CSharp-Vinculum\rlImGui\rlImGui.csproj" />
      <ProjectReference Include="..\..\SoLoud.NET\SoLoud\SoLoud.csproj" />
    </ItemGroup>


    <ItemGroup Condition="Exists('..\..\NekoLib')">
        <ProjectReference Include="..\..\NekoLib\NekoLib\NekoLib.csproj" />
        <ProjectReference Include="..\..\NekoLib\NekoLib.Tools\NekoLib.Tools.csproj" />
        <ProjectReference Include="..\..\NekoLib\NekoLib.Extra\NekoLib.Extra.csproj" />
        <ProjectReference Include="..\..\NekoLib\NekoLib.Filesystem\NekoLib.Filesystem.csproj" />
        <ProjectReference Include="..\..\NekoLib\NekoLib.Console\NekoLib.Console.csproj" />
    </ItemGroup>

    <ItemGroup Condition="!Exists('..\..\NekoLib')">
        <PackageReference Include="VanderCat.NekoLib" Version="0.7.0"/>
        <PackageReference Include="VanderCat.NekoLib.Tools" Version="0.7.0"/>
        <PackageReference Include="VanderCat.NekoLib.Extra" Version="0.7.0"/>
        <PackageReference Include="VanderCat.NekoLib.Filesystem" Version="0.7.0"/>
        <PackageReference Include="VanderCat.NekoLib.Console" Version="0.7.0"/>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="CommandLineParser" Version="2.9.1" />
      <PackageReference Include="ImGui.NET" Version="1.91.6.1" />
      <PackageReference Include="JetBrains.Annotations" Version="2024.3.0" />
      <PackageReference Include="Raylib-CSharp-Vinculum" Version="5.0.1" />
      <PackageReference Include="Serilog" Version="4.2.1-dev-02337" />
      <PackageReference Include="Serilog.Extensions.Logging" Version="9.0.1-dev-02308" />
      <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
      <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
      <PackageReference Include="Tomlyn" Version="0.17.0" />
      <PackageReference Include="YamlDotNet" Version="16.3.0" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="licenses.txt">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </EmbeddedResource>
      <EmbeddedResource Include="bundeledassets\**" Link="%(RecursiveDir)%(Filename)%(Extension)" />
    </ItemGroup>

</Project>
